models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash


class Employee(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.String(10280), nullable=False)
    email = db.Column(db.String(256), unique=True, nullable=False)
    manager_email = db.Column(db.String(502), unique=False, nullable=False)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def __init__(self, username, password, email, manager_email):
        self.username = username
        self.set_password(password)
        self.email = email
        self.manager_email = manager_email


class Manager(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.String(10280), nullable=False)
    email = db.Column(db.String(256), unique=True, nullable=False)
    employees_emails = db.Column(db.String(502), unique=False, nullable=True)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def __init__(self, username, password, email, employees_emails):
        self.username = username
        self.set_password(password)
        self.email = email
        self.employees_emails = employees_emails


class ShiftCalendar(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.Date, nullable=False)
    start_time = db.Column(db.Time, nullable=False)
    end_time = db.Column(db.Time, nullable=False)
    location = db.Column(db.String(2000), nullable=True)
    supervisor = db.Column(db.String(1000), nullable=True)

forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, FileField

__init__.py
from flask import Flask, request, jsonify, render_template, session, flash, redirect, url_for
from flask_sqlalchemy import SQLAlchemy

from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, FileField
import os
from werkzeug.utils import secure_filename
import random


db = SQLAlchemy()


def create_app():
    app = Flask(__name__, static_url_path='/static')

    app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+mysqlconnector://Eddie:Denisdailyvxwx1!@localhost/workscheduler'
    app.secret_key = "Sq88;&3’m"

    from .routes import bp  # Assuming you have a 'routes.py' file
    app.register_blueprint(bp)

    from .models import db
    db.init_app(app)
    return app


# flask run --host=0.0.0.0   run on all devices
'''@app.route('/greet/<name>')
def greet(name):
    return f'Hello, {name}!'''

myapp/routes.py
import werkzeug
from flask import Blueprint, request, render_template, session, flash, redirect, url_for, current_app, \
    send_from_directory
from myapp import db, create_app
from .models import ShiftCalendar, Employee, Manager
# from .forms import ProductForm, lost_and_found_form
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import select
import os
from werkzeug.utils import secure_filename
import random
import json

bp = Blueprint('bp', __name__, static_folder='',
               static_url_path='/static')  # bp = Blueprint('bp', __name__, static_folder='static', static_url_path='/static')


@bp.route("/")
def index():
    # if session['existing_user_login.id']:
    # d = session['existing_user_login.id']
    # return redirect(url_for('bp.home', id=id))
    return render_template('index.html')


@bp.route("/signup", methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        signup_username = request.form.get("signup-username")
        signup_email = request.form.get("signup-email")
        signup_password = request.form.get("signup-password")
        signup_employee_supervisor = request.form.get("signup-es")
        signup_manager_email = request.form.get("signup-manager-email")

        if signup_employee_supervisor == "supervisor":
            existing_username = Manager.query.filter_by(username=signup_username).first()
            existing_email = Manager.query.filter_by(email=signup_email).first()
            if existing_username or existing_email:
                flash("Username or email taken")
                return redirect(url_for('bp.index'))
            else:
                new_user = Manager(username=signup_username, password=signup_password, email=signup_email,
                                   employees_emails="")
                db.session.add(new_user)
                db.session.commit()
        elif signup_employee_supervisor == "employee":
            existing_username = Employee.query.filter_by(username=signup_username).first()
            existing_email = Employee.query.filter_by(email=signup_email).first()
            existing_manager_email = Manager.query.filter_by(email=signup_manager_email)
            if existing_username or existing_email:
                flash("Username or email taken")
                return redirect(url_for('bp.index'))
            else:
                new_user = Employee(username=signup_username, password=signup_password, email=signup_email,
                                    manager_email=signup_manager_email)
                db.session.add(new_user)
                db.session.commit()
    return redirect(url_for('bp.home'))


@bp.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        login_email = request.form.get("login-email")
        login_password = request.form.get("login-password")
        login_em = request.form.get("login-es")

        if login_em == 'login-supervisor':
            existing_user_login = Manager.query.filter_by(email=login_email).first()
            if existing_user_login and existing_user_login.check_password(login_password):
                session['existing_user_login.id'] = existing_user_login.id
                flash('Login successful!')
                session['logged_in'] = True
                return redirect(url_for('bp.home'))
            else:
                flash("Email or password wrong")
                return redirect(url_for('bp.index'))

        elif login_em == 'login-employee':
            existing_user_login = Employee.query.filter_by(email=login_email).first()
            if existing_user_login and existing_user_login.check_password(login_password):
                session['existing_user_login.id'] = existing_user_login.id
                flash('Login successful!')
                session['logged_in'] = True
                return redirect(url_for('bp.home'))
            else:
                flash("Email or password wrong")
                return redirect(url_for('bp.index'))
        else:
            flash("Employee or supervisor not checked")
            return redirect(url_for('bp.index'))

    return redirect(url_for('bp.home'))


@bp.route("/home")
def home():
    shifts = ShiftCalendar.query.all()
    return render_template('home/home.html', shifts=shifts)


@bp.route("/calendar")
def calendar():
    shifts = ShiftCalendar.query.all()
    return render_template('calendar/calendar.html', shifts=shifts)


@bp.route("/request-work-time-change")
def rwtc():
    shifts = ShiftCalendar.query.all()
    return render_template('request-work-time-change/rwtc.html', shifts=shifts)


@bp.route("/get_events")
def get_events():
    events = [
        {'title': 'Event 1', 'start': '2023-11-15'},
        {'title': 'Event 2', 'start': '2023-11-16'},
        {'id': 1, 'title': 'Event 21', 'start': '2023-11-01T10:00:00', 'end': '2023-11-01T12:00:00'},
    ]
    return json.dumps(events)

templates/calendar/calendar.html
<!DOCTYPE html>
<html>
    <!--https://workschedule.net/-->
    <head>
        <title>Work Scheduler</title>
        <script src="../../static/javascript/calendar.js"></script>
        <link rel="stylesheet" href="../../static/css/calendar.css">
        <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.9/index.global.min.js'></script>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Flask Calendar</title>
        <!-- Include jQuery first -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <!-- Include FullCalendar CSS and JS from CDN -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.js"></script>

    </head>
    <body>
        <header>
        </header>
        <div id="sidenav">
            <h2>Home</h2>
            <h2>Calendar</h2>
            <h2>Request work time change</h2>
        </div>
        <main>
            <div id="calendar"></div>
        </main>
    </body>
</html>

templates/home/home.html
<!DOCTYPE html>
<html>
    <!--https://workschedule.net/-->
    <head>
        <title>Work Scheduler</title>
        <script src="../../static/javascript/home.js"></script>
        <link rel="stylesheet" href="../../static/css/home.css">
        <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.9/index.global.min.js'></script>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Flask Calendar</title>
        <!-- Include jQuery first -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <!-- Include FullCalendar CSS and JS from CDN -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.js"></script>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    </head>
    <body>
        <header>
        </header>
        <div id="sidenav">
            <h2><a href="{{ url_for('bp.home') }}">Home</a></h2>
            <h2><a href="{{ url_for('bp.calendar') }}">Calendar</a></h2>
            <h2><a href="{{ url_for('bp.rwtc') }}">Request work time change</a></h2>
        </div>
        <main>
            <div id="calendar"></div>
            <div id="announcements">
                <h1>Announcements</h1>
            </div>
        </main>
    </body>
</html>

templates/index.html
<!DOCTYPE html>
<html>
    <!--https://workschedule.net/-->
    <!--https://sketch.io/sketchpad/-->
    <head>
        <title>WorkFlex</title>
        <link rel="icon" type="image/x-icon" href="../static/images/favicon.png">
    </head>
    <body>
        <header>
            <div id="imgh">
                <img src="../static/images/logo3.png" width="125">
            </div>
            <div id="left">
                <a href="#about-us" class="darkblue">About Us</a>
                <a href="#features" class="darkblue">Features</a>
            </div>
            <div id="right">
                <a id="signup-link1">Sign Up</a>
                <a id="login-link1">Log In</a>
            </div>
        </header>
        <main>
            <div id="sl">
                <div id="login">
                    <h1>Log In</h1>
                    <p>or <a class="lightblue" id="signup-link">sign up</a></p>
                    <br>
                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            <ul class="flashes">
                                {% for message in messages %}
                                    <li style="color: red;">{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    {% endwith %}
                    <form action="/login" method="post">
                        <input class="login-form-input" type="email" placeholder="Email" name="login-email" required><br><br>
                        <input class="login-form-input" type="password" placeholder="Password" name="login-password" required><br><br>

                        <h4>Are you an employee or a supervisor?:</h4><span class="half-br"></span>
                        <input type="radio" id="login-employee" name="login-es" value="login-employee" required>
                        <label for="employee" class="gray">Employee</label>
                        <input type="radio" id="login-supervisor" name="login-es" value="login-supervisor" style="margin-left: 5em;" required>
                        <label for="supervisor" class="gray" >Supervisor</label><br><br><span class="half-br"></span>
                        <br><br><br><br>

                        <button id="login-form-button">Login</button>
                    </form> <!-- change probably -->
                </div>
                <div id="signup" style="display: none;">
                        <form action="/signup" method="post">
                            <div id="part1">
                                <h1>Sign Up</h1>
                                <p>or <a class="lightblue" id="login-link">log in</a></p>
                                <br>
                                <input class="signup-form-input" type="text" placeholder="Username" name="signup-username" required><br><br>
                                <input class="signup-form-input" type="email" placeholder="Email" name="signup-email" required><br><br>
                                <input class="signup-form-input" type="password" placeholder="Password" name="signup-password" required><br><br><br><br>
                                <div id="signup-error"></div>
                                <button type="button" id="signup-continue-button">Continue</button>
                            </div>
                            <div id="part2">
                                <h1>Sign Up</h1>
                                <p>or <a class="lightblue" id="login-link2">log in</a></p>
                                <br><br>
                                <input class="signup-form-input" type="email" placeholder="Supervisor Email ⁽ᴸᵉᵃᵛᵉ ᵇˡᵃⁿᵏ ᶦᶠ ʸᵒᵘ'ʳᵉ ᵃ ˢᵘᵖᵉʳᵛᶦˢᵒʳ⁾" name="signup-manager-email"><br><br><br>
                                <h4>Are you an employee or a supervisor?:</h4><span class="half-br"></span>
                                <input type="radio" id="employee" name="signup-es" value="employee" required>
                                <label for="employee" class="gray">Employee</label>
                                <input type="radio" id="supervisor" name="signup-es" value="supervisor" style="margin-left: 5em;" required>
                                <label for="supervisor" class="gray" >Supervisor</label><br><br><span class="half-br"></span><br>
                                <button type="submit" id="signup-form-button">Sign Up</button>
                            </div>
                        </form> <!-- change probably -->
                    </div>
                </div>
            <div id="blue"> </div>
            <div id="main-content">
                <h2>WorkFlex</h2>
                <br>
                <h1>Empowering Your Work-Life Balance</h1>
                <br><br><br><br>
                <p class="white-green">Revolutionize your productivity with our smart workspace that seamlessly integrates tasks, projects,
                    and collaboration. Customize your schedule, collaborate effortlessly with supervisors, and enjoy
                    transparent time management. WorkFlex: where empowerment meets balance. Sign up today and redefine
                    your work-life harmony!</p>
            </div>
            <div id="content">

            </div>
        </main>
    </body>
</html>
<script src="../static/javascript/script.js"></script>
<link rel="stylesheet" href="../static/css/styles.css">

templates/request-work-time-change/rwtc.html
<!DOCTYPE html>
<html>
    <!--https://workschedule.net/-->
    <head>
        <title>Work Scheduler</title>
        <script src="../../static/javascript/rwtc.js"></script>
        <link rel="stylesheet" href="../../static/css/rwtc.css">
        <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.9/index.global.min.js'></script>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Flask Calendar</title>
        <!-- Include jQuery first -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <!-- Include FullCalendar CSS and JS from CDN -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.js"></script>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    </head>
    <body>
        <header>
        </header>
        <div id="sidenav">
            <h2><a href="{{ url_for('bp.home') }}">Home</a></h2>
            <h2><a href="{{ url_for('bp.calendar') }}">Calendar</a></h2>
            <h2><a href="{{ url_for('bp.rwtc') }}">Request work time change</a></h2>
        </div>
        <main>
            <div id="rwtc">
                <h1>Request Work Time Change</h1>
                
            </div>
        </main>
    </body>
</html>